server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: h2
    
  datasource:
    url: jdbc:h2:mem:basic
    driverClassName: org.h2.Driver
    username: sa
    password:

  thymeleaf:
    cache: false
    
    