server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database: mysql
    
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootbasic?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: limstar0724

  thymeleaf:
    cache: false
